# Generated by Django 3.1 on 2023-08-06 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('contents', models.TextField(verbose_name='本文')),
                ('posted_at', models.DateField(auto_now_add=True, verbose_name='投稿日時')),
                ('category', models.CharField(choices=[('science', '科学のこと'), ('daialy', '日常のこと'), ('music', '音楽のこと')], max_length=50, verbose_name='カテゴリ')),
            ],
        ),
    ]
